return {
  ["workshop-374550642"]={
    configuration_options={
      STACK_SIZE_LARGEITEM=99,
      STACK_SIZE_MEDITEM=99,
      STACK_SIZE_PELLET=120,
      STACK_SIZE_SMALLITEM=99,
      STACK_SIZE_TINYITEM=99 
    },
    enabled=true 
  },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-380423963"]={
    configuration_options={
      [""]=0,
      boulder_blue=0.2,
      boulder_purple=0.05,
      change_cave_loot=false,
      common_loot_charcoal=0,
      common_loot_flint=0.35,
      common_loot_rocks=0.35,
      cutlichen=0,
      durian=0,
      flintless_blue=0.5,
      flintless_purple=0.1,
      flintless_red=0.2,
      foliage=0,
      gears=0,
      goldvein_purple=0.05,
      goldvein_red=0.1,
      guano=0,
      ice=0,
      lightbulb=0,
      moon_green=0.02,
      moon_orange=0.02,
      moon_yellow=0.02,
      pinecone=0,
      rare_loot_bluegem=0.015,
      rare_loot_marble=0.015,
      rare_loot_redgem=0.015,
      rottenegg=0,
      seeds=0,
      spoiled_food=0,
      stalagmite_green=0.02,
      stalagmite_orange=0.02,
      stalagmite_yellow=0.02,
      uncommon_loot_goldnugget=0.05,
      uncommon_loot_mole=0.05,
      uncommon_loot_nitre=0.05,
      uncommon_loot_rabbit=0.05 
    },
    enabled=true 
  },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-786556008"]={
    configuration_options={ ENABLEBACKPACK=false, EXTRASLOT=0, INVENTORYSIZE=25 },
    enabled=true 
  } 
}