return {
  ["workshop-1803285852"]={
    configuration_options={
      [""]=0,
      AutoPickupAsh=false,
      AutoPickupEnabled=false,
      AutoPickupPoop=false,
      AutoPickupRange=10,
      AutoPickupSeeds=false,
      AutoStackAsh=false,
      AutoStackEnabled=true,
      AutoStackMakeNewStackMainStack=false,
      AutoStackManuallyDroppedItems=true,
      AutoStackPoop=false,
      AutoStackRange=10,
      AutoStackSeeds=false,
      AutoStackTwiggyTreeTwigs=false,
      ManualDropStackRange=5,
      ManualStackAsh=false,
      ManualStackMakeNewStackMainStack=false,
      ManualStackPoop=false,
      ManualStackSeeds=false,
      PlayerMustHaveOneOfItemToAutoPickup=false,
      SmokePuffOnStacking=true,
      StackDuringPopulation=false 
    },
    enabled=true 
  },
  ["workshop-786556008"]={
    configuration_options={ ENABLEBACKPACK=false, EXTRASLOT=0, INVENTORYSIZE=25 },
    enabled=true 
  } 
}