return {
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1530801499"]={
    configuration_options={
      ArrowsignEnable=false,
      CountdownEnable=false,
      HungerCost=1,
      Ownership=true,
      SanityCost=1 
    },
    enabled=true 
  },
  ["workshop-1803285852"]={
    configuration_options={
      [""]=0,
      AutoPickupAsh=false,
      AutoPickupEnabled=false,
      AutoPickupPoop=false,
      AutoPickupRange=10,
      AutoPickupSeeds=false,
      AutoStackAsh=false,
      AutoStackEnabled=true,
      AutoStackMakeNewStackMainStack=false,
      AutoStackManuallyDroppedItems=true,
      AutoStackPoop=false,
      AutoStackRange=10,
      AutoStackSeeds=false,
      AutoStackTwiggyTreeTwigs=false,
      ManualDropStackRange=5,
      ManualStackAsh=false,
      ManualStackMakeNewStackMainStack=false,
      ManualStackPoop=false,
      ManualStackSeeds=false,
      PlayerMustHaveOneOfItemToAutoPickup=false,
      SmokePuffOnStacking=true,
      StackDuringPopulation=false 
    },
    enabled=true 
  },
  ["workshop-1852257480"]={
    configuration_options={ horizontal=0, info=false, position="bottom", vertical="auto" },
    enabled=true 
  },
  ["workshop-1951468597"]={
    configuration_options={
      CanSpawnSpore=true,
      HouseHammered=true,
      NewInteriors=true,
      NewWalls=true,
      Tardis=true 
    },
    enabled=true 
  },
  ["workshop-2078243581"]={
    configuration_options={ Blue=0, Display="target", Green=0, Projectile=true, Red=1, Type="hit" },
    enabled=true 
  },
  ["workshop-374550642"]={
    configuration_options={
      STACK_SIZE_LARGEITEM=99,
      STACK_SIZE_MEDITEM=99,
      STACK_SIZE_PELLET=120,
      STACK_SIZE_SMALLITEM=99,
      STACK_SIZE_TINYITEM=99 
    },
    enabled=true 
  },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-380423963"]={
    configuration_options={
      [""]=0,
      boulder_blue=0.2,
      boulder_purple=0.05,
      change_cave_loot=false,
      common_loot_charcoal=0,
      common_loot_flint=0.35,
      common_loot_rocks=0.35,
      cutlichen=0,
      durian=0,
      flintless_blue=0.5,
      flintless_purple=0.1,
      flintless_red=0.2,
      foliage=0,
      gears=0,
      goldvein_purple=0.05,
      goldvein_red=0.1,
      guano=0,
      ice=0,
      lightbulb=0,
      moon_green=0.02,
      moon_orange=0.02,
      moon_yellow=0.02,
      pinecone=0,
      rare_loot_bluegem=0.015,
      rare_loot_marble=0.015,
      rare_loot_redgem=0.015,
      rottenegg=0,
      seeds=0,
      spoiled_food=0,
      stalagmite_green=0.02,
      stalagmite_orange=0.02,
      stalagmite_yellow=0.02,
      uncommon_loot_goldnugget=0.05,
      uncommon_loot_mole=0.05,
      uncommon_loot_nitre=0.05,
      uncommon_loot_rabbit=0.05 
    },
    enabled=true 
  },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-604761020"]={
    configuration_options={
      baoshibaolv=1,
      blue_baoshi=1,
      er_shuoming=0,
      green_baoshi=1,
      huangjinbaolv=1,
      marble_suipian=1,
      orange_baoshi=1,
      purple_baoshi=1,
      red_baoshi=1,
      RUOYINXIAN=false,
      SHENGDANSHI=false,
      shishengzhang=0,
      shitoubaolv=1,
      thulecite_xiukuang=1,
      wajuecishu=2,
      yellow_baoshi=1,
      yi_shuoming=0 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-786556008"]={
    configuration_options={ ENABLEBACKPACK=false, EXTRASLOT=0, INVENTORYSIZE=25 },
    enabled=true 
  },
  ["workshop-791838548"]={
    configuration_options={
      Building_SD=33,
      building_upgradeable="y",
      buildinglimit=true,
      Buildings=0,
      Dispenser=0,
      Dispenser_Difficulty="default",
      dispenseramount=4,
      dispenserhealingrate=3,
      dispenserlimit=true,
      disprange=3,
      ehardhatdura=295,
      EHat_Difficulty="default",
      engiedmgdebuff=0.8,
      engiesciencebonus=1,
      engineer_health=125,
      engineer_hunger=150,
      engineer_sanity=200,
      eteleport_penalty=5,
      hardhatabsorb=0.7,
      pda_Difficulty="default",
      pda_ingredientpercent=0.9,
      Scrap_Difficulty="default",
      ["Sentry Gun"]=0,
      Sentry_Damage=10,
      Sentry_Difficulty="default",
      sentry_ff="noff",
      sentry_ff_wall="noff",
      sentry_healinghit=10,
      Sentry_Health=200,
      Sentry_Range=13,
      Sentry_ROF=1,
      sentryamount=4,
      sentryh_regen="n",
      sentrylimit=true,
      starting_scrap="y",
      Teleporter_Difficulty="default",
      teleporteramount=4,
      teleporterlimit=true,
      Teleporters=0,
      tf2Wrench_Difficulty="default",
      tf2wrenchdmg=17,
      tf2wrenchuses=150,
      ["The Engineer"]=0,
      toolbox_penalty=0.15,
      Tools=0 
    },
    enabled=true 
  } 
}